files-to-inspect:
  - http://dev138.mw.lab.eng.bos.redhat.com/candidate/JBDV/JBDV-6.4.0.CR2/jboss-dv-6.4.0-maven-repository.zip
maven-config:
  xsd-schema: http://maven.apache.org/maven-v4_0_0.xsd
jdk-version: 1.8
maven-repo:
  main-group-id: org.jboss.jdv
  known-classifiers:
  - bundle
  - processor
  - shaded
  - tck
  expected-boms:
  - org.jboss.jdv:jboss-dv
  internal-maven-repos:
  - http://download.eng.bos.redhat.com/brewroot/repos/jb-dv-6.4-build/latest/maven
  unique-artifacts-exceptions:
  - com.fasterxml:oss-parent
  - com.fasterxml.jackson:jackson-parent
  - org.jboss:jboss-parent
  - org.slf4j:slf4j-parent
  - org.sonatype.oss:oss-parent
  # the above are fairly typical exceptions (parent POMs), the below I don't understand
  - com.fasterxml.jackson.core:jackson-core
  unexpected-files-exceptions:
  - kubernetes-model-*-schema.json
  - vertx-web-*-client.js
  - infinispan-*-features.xml
  osgi-versions-exceptions:
  - hamcrest-parent-1.3-redhat-1.pom
  - hamcrest-core-1.3-redhat-1.pom
  - jboss-component-version-master-6.0.1-redhat-1.pom
  - jboss-dependency-management-all-6.0.1-redhat-1.pom
  - jboss-dependency-management-build-6.0.1-redhat-1.pom
  - jboss-dependency-management-eap-6.0.1-redhat-1.pom
  - jboss-parent-9-redhat-1.pom  
